release: "pm"

applications:
  # Wekan
  - name: wekan
    enabled: false
    source: https://github.com/wekan/wekan.git
    source_path: helm/wekan
    source_ref: "v4.41"
    values:
      service:
        type: ClusterIP
      autoscaling:
        enabled: false
      mongodb-replicaset:
        replicas: 1
        securityContext:
          runAsUser: ""
          fsGroup: ""
      ingress:
        enabled: false
      route:
        enabled: true
  # Mattermost
  - name: mattermost
    enabled: false
    source: https://github.com/mattermost/mattermost-helm.git
    source_path: charts/mattermost-team-edition
    source_ref: "mattermost-team-edition-3.16.0"
    values:
      route:
        enabled: true
      mysql:
        mysqlRootPassword: "mysqlpass"
        mysqlUser: "mattermost"
        mysqlPassword: "matterpass"
  # Etherpad
  - name: etherpad
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/etherpad
    source_ref: "etherpad-0.0.7"

  # Owncloud
  - name: owncloud
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/owncloud
    source_ref: "owncloud-0.0.2"
    values:
      route:
        enabled: true
      hostname: owncloud.apps.hivec.sandbox1559.opentlc.com
    ignore_differences:
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
          - /spec/template/spec/containers/0/image
          - /spec/triggers/0/imageChangeParams/lastTriggeredImage

  # Hashicorp Vault
  - name: vault
    enabled: false
    source: https://github.com/hashicorp/vault-helm.git
    source_path: .
    source_ref: "v0.7.0"
    values:
      global:
        tlsDisable: false
        openshift: true
      injector:
        enabled: false
        route:
          enabled: true
          host: '""'
      server:
        service:
          annotations:
            service.beta.openshift.io/serving-cert-secret-name: vault-tls
        extraVolumes:
          - type: secret
            name: vault-tls
        standalone:
          config: |
            ui = true
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
              tls_key_file  = "/vault/userconfig/vault-tls/tls.key"
            }
            storage "file" {
              path = "/vault/data"
            }
